{{- if and .Values.licenseKey.createSecret .Values.enableAES }}
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.licenseKey.secretName }}
  name: {{ .Values.licenseKey.secretName }}
  {{- else }}
  name: {{ include "ambassador.fullname" . }}-edge-stack
  {{- end }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  license-key: {{- if .Values.licenseKey.value }} {{ .Values.licenseKey.value | b64enc }} {{- else }} "" {{- end }}
{{- end }}
